spring:
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hosteldb
    username: postgres
    password: postgres.
  flyway:
    baseline-on-migrate: true
server:
  port: 8060
  error:
    include-message: always
    include-binding-errors: always

image:
  path: /home/sultan/data/imageUsers
path:
  default:
    image:
      user: /home/sultan/data/imageUsers/image.png